### ISSUE TITLE
The code sends the labels obtained from the dataset to the plot_z_run function

### ISSUE THREAD

**Issue by tharunShiv** [RobRomijnders/AE_ts#8]
**Isn't it supposed to be Unsupervised?** 
What if we had datasets with no labels and we wanted to visualize the resultant clusters. 
Where are they?  How do we obtain them?

@RobRomijnders @tejaslodaya

**Comment by tejaslodaya** [comment]
Hi @tharunShiv ,

This algorithm is completely unsupervised. The labels are a way of generating different colors for us to confirm the results. As you can see, same colored data points form a small cluster. This is a way of testing if the algorithm works. 

If in your case, there's no actual labels, one workaround to confirm the results is to run k-means algorithm on top of the generated latent vectors (`z_run`) and use the generated kmeans_labels to form colors.

Let me know if it makes sense. 

Also, I'm coming up with a pytorch version of the VRAE algorithm. So, stay tuned!

**Comment by RobRomijnders** [comment]
Wow, thank you @tejaslodaya for the quick comment. Keep me updated on your project!

**Comment by tharunShiv** [comment]
If we are not able to get the labels, then what did we infer from the ECG5000 using this model?
@tejaslodaya @RobRomijnders 
What can we use the generated latent vectors for? What is their purpose? What can we use them for?

@tejaslodaya  Amazing! Looking forward to your pyTorch version.

**Comment by tejaslodaya** [comment]
Hi @tharunShiv ,

The latent vectors are a dense representation of the actual timeseries (think of it as a squished vector). Another way of saying it is that the latent vector completely and independently represents the entire timeseries. 

As said earlier, you can still run k-means on top of the latent vectors to get labels.
Since this is an unsupervised learning task, you can do a host of things with squished latent vector (hint: anomaly detection, dimensionality reduction, etc..)

Also, it wouldn't hurt to have a look at applications of autoencoders. 

@RobRomijnders please close this issue.
Thanks

**Comment by tharunShiv** [comment]
Thank You @tejaslodaya 
Thank You @RobRomijnders 
This topic seems very complex to me, sorry if I seemed stupid by asking such questions. I just didn't want to remain stupid at this topic.

And yeah I knew the applications of AE, right from their applications at image colourization, anomaly detection, noise filtering capabilities, restoring missing patches on images and other generative applications similar to GANs.
But I wanted to know this code in detail, anyways Thank you for your time!!

**Comment by tejaslodaya** [comment]
Hi @RobRomijnders @tharunShiv 

Here's a pytorch version of the above code!
Link: https://github.com/tejaslodaya/timeseries-clustering-vae

This was in pipeline from a few days. Wished to push it before holidays!
Happy holidays!
